# .cpanel.yml
---
deployment:
  tasks:
    - export DEPLOYPATH=/home//ayvyxx1tqw2s/public_html/
    - /bin/mkdir -p "$DEPLOYPATH"
    - /bin/rsync -a --delete --exclude ".git" --exclude ".gitignore" ./ "$DEPLOYPATH"
