[build]
command = '''
git clone https://github.com/flutter/flutter.git -b stable --depth 1
export PATH="$PATH:`pwd`/flutter/bin"
flutter --version
flutter config --enable-web
flutter doctor
flutter pub get
flutter build web --release --base-href /
# تأكد من وجود ملف _redirects
echo "/*    /index.html   200" > build/web/_redirects
# إنشاء الأيقونات (ملفات PNG)
mkdir -p build/web/icons
# إنشاء أيقونات PNG بسيطة باستخدام base64
cat <<EOT > build/web/icons/Icon-192.png
iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAMAAABlApw1AAAACVBMVEUAplEAAAD///+g8ry/AAAAA3RSTlP//wDXyg1BAAAASklEQVR42u3BAQ0AAADCIPuntscHFQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACA5wEsEAAB1cW+6gAAAABJRU5ErkJggg==
EOT
cat <<EOT > build/web/icons/Icon-512.png
iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAMAAADDpiTIAAAACVBMVEUAplEAAAD///+g8ry/AAAAA3RSTlP//wDXyg1BAAAASklEQVR42u3BAQ0AAADCIPuntscHFQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACA5wEsEAAB1cW+6gAAAABJRU5ErkJggg==
EOT
# إصلاح ملف index.html للتعامل مع مشكلة _flutter وتحديث meta tags
sed -i 's/<meta name="apple-mobile-web-app-capable" content="yes">/<meta name="mobile-web-app-capable" content="yes">\\n  <meta name="apple-mobile-web-app-capable" content="yes">/g' build/web/index.html
# تأكد من أن flutter.js يتم تحميله قبل استخدام _flutter
cat <<EOT > build/web/flutter-init.js
window.addEventListener('load', function() {
  // تهيئة _flutter إذا لم يكن موجودًا
  if (typeof _flutter === 'undefined') {
    window._flutter = {
      loader: {
        loadEntrypoint: function(config) {
          // تحميل main.dart.js
          var scriptTag = document.createElement('script');
          scriptTag.src = 'main.dart.js';
          document.body.appendChild(scriptTag);
        }
      }
    };
  }
});
EOT
# إضافة script لتعريف _flutter في بداية الملف
sed -i '/<head>/a \\  <script src="flutter-init.js"><\\/script>' build/web/index.html
'''
publish = "build/web"

[build.environment]
CI = "false"
NODE_VERSION = "18"
'''
publish = "build/web"

[build.environment]
CI = "false"
NODE_VERSION = "18"
