[build]
  command = """
    git clone https://github.com/flutter/flutter.git -b stable --depth 1
    export PATH="$PATH:`pwd`/flutter/bin"
    flutter --version
    flutter config --enable-web
    flutter doctor
    flutter pub get
    flutter build web --release --base-href /
    
    # تأكد من وجود ملف _redirects
    echo "/*    /index.html   200" > build/web/_redirects
    
    # تأكد من وجود مجلدات الأيقونات وإنشائها
    mkdir -p build/web/icons
    
    # نسخ الأيقونات من مجلد web إلى build/web
    cp -f web/icons/Icon-192.png build/web/icons/Icon-192.png || echo "فشل نسخ Icon-192.png"
    cp -f web/icons/Icon-512.png build/web/icons/Icon-512.png || echo "فشل نسخ Icon-512.png"
    
    # نسخ flutter-init.js إلى مجلد build/web 
    cp -f web/flutter-init.js build/web/flutter-init.js || echo "فشل نسخ flutter-init.js"
    
    # تعديل ملف index.html لإصلاح مشكلة _flutter وتحديث meta tags
    sed -i 's/<meta name="apple-mobile-web-app-capable" content="yes">/<meta name="mobile-web-app-capable" content="yes">\\n  <meta name="apple-mobile-web-app-capable" content="yes">/g' build/web/index.html
    sed -i '/<head>/a \\  <script src="flutter-init.js"><\\/script>' build/web/index.html
    
    # عرض محتويات مجلد الأيقونات للتأكد
    ls -la build/web/icons/
  """
  publish = "build/web"

[build.environment]
  CI = "false"
  NODE_VERSION = "18"
