[build]
command = """
curl -L -o flutter.tar.xz https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.19.3-stable.tar.xz && 
tar xf flutter.tar.xz && 
export PATH="$PATH:`pwd`/flutter/bin" &&
flutter precache &&
flutter --version &&
flutter build web --release &&
echo '<script>window.addEventListener("load", function() { _flutter = { loader: {} }; _flutter.loader.loadEntrypoint({ serviceWorker: { serviceWorkerVersion: null }, onEntrypointLoaded: function(e) { e.initializeEngine().then(function(e) { e.runApp() }) } }) });</script>' >> build/web/index.html
"""
"""
publish = "build/web"

[build.environment]
CI = "false"
NODE_VERSION = "18"
