[build]
  command = """
    # Download and setup Flutter
    git clone -b stable https://github.com/flutter/flutter.git --depth 1
    export PATH="$PATH:$(pwd)/flutter/bin"
    flutter precache --web
    flutter doctor -v
    
    # Get dependencies and build
    cd "$PWD"
    flutter clean
    flutter pub get
    flutter config --enable-web
    flutter build web --release --dart-define=Dart.vm.product=true
  """
  publish = "build/web"

# Environment variables for all deploy contexts
[build.environment]
  CI = "false"
  NODE_VERSION = "22.0.0"
