# netlify.toml - ملف إعدادات مبسط
[build]
  command = "bash netlify-build.sh"
  publish = "build/web"

[build.environment]
  NODE_VERSION = "20"

# إعادة توجيه كل الروابط للصفحة الرئيسية (مهم للـ SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
