[build]
command = '''
git clone https://github.com/flutter/flutter.git -b stable --depth 1
export PATH="$PATH:`pwd`/flutter/bin"
flutter --version
flutter config --enable-web
flutter doctor
flutter pub get
flutter build web --release
mkdir -p public
cp -r build/web/* public/
cp custom_index.html public/index.html
'''
publish = "public"

[build.environment]
CI = "false"
NODE_VERSION = "18"
