name: bunyan
description: A Flutter application for Bunyan platform

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  provider: ^6.1.1
  # قواعد البيانات والمصادقة
  sqflite: ^2.3.0
  path: ^1.8.3
  crypto: ^3.0.3
  http: ^1.1.0
  path_provider: ^2.1.1
  # أمان وتشفير
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.0.0
  # UI enhancements
  google_fonts: ^6.1.0
  animations: ^2.0.8
  url_launcher: ^6.3.2
  lottie: ^2.6.0
  flutter_local_notifications: ^16.1.0
  sqflite_common_ffi: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/l10n/
    - assets/images/
