[build]
  command = "bash setup.sh && bash netlify-build.sh"
  publish = "build/web"

[build.environment]
  NODE_VERSION = "20"
  FLUTTER_VERSION = "stable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
