[build]
  command = "git clone https://github.com/flutter/flutter.git --depth 1 -b stable $HOME/flutter && export PATH=$PATH:$HOME/flutter/bin && flutter doctor && flutter pub get && flutter build web -t lib/main_selector_page.dart --release --base-href /"
  publish = "build/web"

[build.environment]
  NODE_VERSION = "20"
  FLUTTER_VERSION = "stable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
