[build]
  publish = "build/web"
  command = "bash netlify-build.sh"

[build.environment]
  NODE_VERSION = "22"
  FLUTTER_VERSION = "stable"

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
