# اكتب ملف netlify.toml من جديد بقسم build.environment واحد
Set-Content netlify.toml @'
[build]
  publish = "build/web"
  command = "bash netlify-build.sh"

[build.environment]
  NODE_VERSION   = "22"     # أو "20" لو حاب LTS
  FLUTTER_VERSION = "stable"

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
'@ -Encoding utf8
